# MongoDB Configuration File

# Where and how to store data.
storage:
  dbPath: D:\workplace\idea\agent-browser\mongodb-data

# where to write logging data.
systemLog:
  destination: file
  path: D:\workplace\idea\agent-browser\mongodb-data\mongod.log
  logAppend: true

# network interfaces
net:
  port: 27017
  bindIp: 127.0.0.1